language: node_js
node_js: node
branches:
  only:
  - /.*/
before_install:
- npm install mocha -g
- npm install typescript -g
install:
- npm install
script: npm test
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: npm
  email: awsdfgvhbjn@gmail.com
  api_key:
    secure: KH+rtZ6b+uiuVVAAuZ+rtZBKFuhY/c+p1svhq21m05UzzwCNhAKpUsz8B+y/QwmyrhSwAz8wBI0+deG2AbB5Pm5+jS1AyasszrmCn9WL7gSoV9WM8r5EptNPgLwO65lqzZEuWBdrvoHgF20KtmdKxvSfI5H7IaNQZAzQ5dYUudWFKecRLyFLg0mPA0zNsWtFeBqegxFPjhFSI5u/arOJVSmTFBzsjtRsO8y9bLkNpclzEi6BpoV0355qLeaZwc/FT/57RWEnVmLb25KDvitR2jjHx50axFeKx/h4OvigrrTbYWzX+vSWss/2wP0oL+En692b45FJu93gdGdAweNbiE67VrPWPTAaEY0ibA3C2X8phauBuiQWF36ckGcqzZQZBCnoD/1sbAsfhBeOJRFrqvgZeWuV9zXtHKFDjjaeE3njwcbvltucvfEXM9OvL617waAEBYrC8JElQM1MZxewRzujC9o8fhU+Dr9RpApN75Y3ObU1u3PPOodczcdblewkyidAvsFJ/oo0x20AxL8Aj+iRb70mIcdLgSPiJO6sPiksIN8uvfJj3aG9kNBJSc1yaHabSMewcD2ymH1F578ag0NgWNEdl50YxXVfqERXba0st2EaK4p3ZERb7P96Ih8pLQcmr/nfjvgzfFzEQSGQ/fKn6++MH2ASswjb1GFHacc=
  on:
    tags: true
    repo: SanderRonde/html-typings