language: node_js
node_js: node
branches:
  only:
  - "/.*/"
before_install:
- npm install mocha -g
- npm install typescript@latest -g
install:
- npm install
script:
- npm test
- tsc
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: npm
  email: awsdfgvhbjn@gmail.com
  api_key:
    secure: L6kTnG130X0SaPMvLfRUkgAArKw+Xm5W+vHTnzuWi/1ehT7eQhanUvb7Hhj/Et1yDlnZHcF99eIWYdyHCnjWEaaybSv+rTjJsGFKdrR37Xk2gXfTwLQNHDyODGy1FmHgpSwD6NK4MY7PqcdcQMEDl2zHDzFgJZJ0KD3lIpHnOj/zYcsYzGTbqyPcT8SsbuerrAykM7M1QoJa/p1KgUoZdYHDdFZBN5pWI6FA01xvUa+3ngI3tZNtKqhEbR5RVq6nFvULc8SFUV5EB2x3wM1WlGyJC03qf6FlOkkuF8Mu92DXYCCfMUyXCZRTtkq56l2VbBPYXrxCEZDJaFTLdS0DJp3dthspDtAKV4njm4NIVt4ZFmvo9odKWn5Gu73+5rdXO8n6d+MJql+rnHAhlL4Xh/QDtWHGdoPR9DfUxKPdoZVh20lm3mZzAuTMxCd/56eMQ3BU9uoLvnEFwrqjrIGZ+wCg9Luy5+Mzez4g7q18q/KGpXrVrna9LBI5L4mhP805ms8xiu+qfvmtjIEMN2UOgZXj6zGjw2djHdPJkieAY6Ti/BFcyzSCNRgQVraTN6Wma5PVg0w3XnWWSyNR1uudZxemsvspyWKhto/4aKEKrTygXwGXX1deC4YShMdBIbiw2CRWt9K5AQ7w2l8lNNQmPs3oxbnyRr+A8G03DMlmhY8=
  on:
    tags: true
    repo: SanderRonde/html-typings