language: node_js
node_js: node
branches:
  only:
  - "/.*/"
before_install:
- npm install mocha -g
install:
- npm install
script:
- npm test
- tsc

before_deploy:
- grunt copyFiles
- grunt genDefs
- tsc

notifications:
  email:
    on_success: change
    on_failure: change
deploy:
- provider: npm
  email: awsdfgvhbjn@gmail.com
  skip_cleanup: true
  api_key:
    secure: GISRvThQeRz1+PwNmc1VIguXfiG+8Q+QD/EksxjbCVPdVWo3eiUqXIVbpez8UwHh9QKD53KwYPknspdbAfV7LFqHQh0dxMm5KS+4pKZYyNMNCCNevD+SYPikIw71zEMgzxBMIPcCAOKqHWHuLu3A5XQ0xrCeERWBToPZ76SRd5Q+/D4Ep5F1rRdICnUe2X9mXLUMiWRT6szgfr/h8qgGFDwlSo4J5hjGr/8VdRx47Rz8mcXI3UT8BDzQ6tskmJ+ZTeYJJrcrPZceoyn6vIh7BuD0++hU3r7yamhHUrpCfXxZyeUPzKda83YtsY/Vzk9asyQ7nq7x5gb8/euIDuh6tNRj/uyM21niPlUhb1S5Ti2xxQLO2eYG/8w9AQiBCfXlt3eHv37OXrjVWpZcD0eGbY3DOrL+XDZbuabLt84G/I3s52dGlhHAPaWF4iXN+uuVNGTTlrLK75rQ4DBSaMfMZrZWkjaqz12cH6YU8DdFEM5owpgcPEvb/E7r+le7+G+JistHgiHSNZV8Z75zqNuPCKWrYIBn/VWu1T4+Xn1KHapBgZbJ8Gl9QPqm2GQPSgV+LSew9jE936wSm+1v/C/hdjJHop9DubrRyZKb4o/AXrlMcrIr+dJBR94OwPJBVrlr3GajgtwZC2axuCpTYAFG/1Gq3L2iSS2jdIoHBYEix2g=
  on:
    tags: true
    repo: SanderRonde/html-typings
- provider: pages
  github_token:
    secure: UFctagThzxlZGFZW0ps2mafgZaSl2Xa1Ow36BTYbYaEMMbxjmW6UbNAu9Q/HXWiuE97B8RbCw32gym+ywnvvixjwd+371RIYrKNASA2Sc6Ul17+nclgv0tLxvjVS1IF1GaFu/woui4HEmoaGlPm8gbEm/rttZCeGwSMnnfnjsClGVT9qetF/hYjFFDtKQolmaHyJIQjm0Adad1W/utwieSkLlkSp+VfvjDq52Ryg0QzELvSrva9zvZ/Ui61/1ICf8sZ0oox+I73LOr/OR2fbRfcMjQjSCBe6YIbM2rZCYIfmsNfAuHXtvRW3Pef84g7oG+IaZpApYSYNh/eQJl5h8cBwf7rx6SlvmpNO9H7Kmg+NiYCODYREMJOADaHt4i3J1emRcf36faOAOEXv5Nn3XN7GieZYIk0ns3LQV2ynPCwjV8qKYF1Ghbx0sz/sQbKnjdOYCMSxjJHkUjs6NzQqWVWLsKfi2MbPactiNWUgAbsgroM2TFntMx8ew0+KeySacQCf5TbYSIreNECR9Iz9kXbcd/HG1TysEjWzHG1rtyEOlA5d48mg2XKtSZ9WPcbAya5FbPSdubo/UDOxceenKFbXDRkneCKyXKzz6b9UWgwwXa/WlHOSxyAHmy1SiO6RWfOUrhjfCTSHZWBp7LKCR4wVAkNuBd/FHGRJvIDZ498=
  keep_history: true
  on:
    branch: master
  local_dir: "./docs"