language: node_js
node_js: node
branches:
  only:
  - master
  - beta
before_install:
- npm install mocha -g
- npm install typescript -g
install:
- npm install
script: npm test
notifications:
  email:
    on_success: change
    on_failure: change