language: node_js
node_js: node
branches:
  only:
  - /.*/
before_install:
- npm install mocha -g
- npm install typescript@latest -g
install:
- npm install
script:
- npm test
- tsc
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: npm
  email: awsdfgvhbjn@gmail.com
  skip_cleanup: true
  api_key:
    secure: X5XU/fXeF4IocjblhCMB7oz9VDMCRXGTPyMw4PebGuFKzrMNbL7N8MPmuiLDBbAyu+I1S7IRpyCHdfwc0n9Zyb5kbkMD4Hp5CnTrGEQNFMdVGc1QUcX+SCQ73cB/YOF3WXVhOJK7qt8OWS7LgecSkVMTu0dwtj5M6NZzb4aCQ8QlltKvypc/4nR+WyQm38DtEJ9ZwTGq6xWB8DbIaHHWefrwxWcycpnyHUhG4M8zRCKGxNtbrJKQA8gdFA1OBoFBCPVFX04Prlv4diSTL0EH4ms6WXsq2u6gAc++6qxle1Mi2MHA2CzxK9vbJvvMrhobWyia6eRjkOWCSaiLdbpPCDAVKpPhC5otFW4L97nXo603u1Ujv96UuNFJWM+MoAGW89HvWpoGfhajwkSu4Tpx8e94kouKf0z4dvIaAmOAoR7MtAFev1Zd36F59YPkpjTjMcPstcitzNpmxgo8GAu87nb3jrtFmxqIpyc7rXM3y6RLAXUaZ6wf4/RxJNISrv7eY0Yg4SeTVUDFb04eRjX1El/kmOVyNqKfoOlUo8aoyf/NCYwB9qOSdPY7V9MvHSoX5MrcD7f3wpnu6ou/rCTaPX167Z14zP9FNQEx89XWrZdxnQGn9LhmEtVMbT9c6GuT568YVmvWpePckGRQggrHynRX6+59moZs83Dj8FLZwN4=
  on:
    tags: true
    repo: SanderRonde/html-typings